version: "3.2"

services:
  menu-api:
    container_name: menu-api
    image: giirochas/ms-menu:latest
    ports:
      - "9000:8080"       
  
  order-api:
    container_name: order-api
    image: order_api
    build:
      context: ./ms-order
    ports:
      - "8000:8081"       

  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: microservices-development
    ports:
      - "27017:27017"